services:
  chatnetmedgpt-api:
    image: gitlab.cosy.bio:5050/simonsuewer/chatnetmedgpt-api
    volumes:
      - ./chatnetmedgpt/api/data:/app/data
      - ./chatnetmedgpt/api/model:/app/model
    ports:
      - "8145:8000"
    restart: on-failure
  chatnetmedgpt-frontend:
    image: gitlab.cosy.bio:5050/simonsuewer/biomedformerui/ui-chat:latest
    ports:
      - "8144:4000"
    volumes:
      - ./biomedformer-data/:/app/browser/public/data
    restart: on-failure